name: auto approve and merge and tidy
on: pull_request

# job level conditions don't seem to work at the moment
# https://github.community/t5/GitHub-Actions/Status-of-workflows-with-no-running-jobs/td-p/37160
# which is why github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' is
# repeated over and over
jobs:
  approve:
    name: auto-approve dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: approve
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
  merge:
    name: auto-merge dependabot PRs
    runs-on: ubuntu-latest
    needs: [approve]
    steps:
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: 'WyriHaximus/github-action-wait-for-status@v1.0.0'
        with:
          ignoreActions: merge
          checkInterval: 13
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: merge
        uses: actions/github-script@0.2.0
        if: (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]') && steps.waitforstatuschecks.outputs.status == 'success'
        with:
          script: |
            github.pullRequests.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: '${{ secrets.GITHUB_TOKEN }}'
